version: '3'
services:
  neo4j:
    image: neo4j:3.5
    hostname: neo4j
    volumes:
      - $HOME/neo4j/data:/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: none
  app:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: test123
      NEO4J_URI: bolt://neo4j:7687
    depends_on:
      - neo4j